### ISSUE TITLE
Can't we remove context from project ?

### ISSUE THREAD

**Issue by pathirana** [gor181/react-notification-system-redux#18]
Can't we remove context api from this module ? Because react not recommend using that Api.

**Comment by gor181** [comment]
hi @pathirana ,

Thanks for reaching out.

We currently use it at: https://github.com/gor181/react-notification-system-redux/blob/master/src/notifications.js#L30 to hide the notification, otherwise this should be done manually in each `onRemove` handler you pass in.

We can check for a `this.context.store` and execute the dispatch if exists, otherwise we can ignore that action.

Redux is using context therefore if redux ceases to exist or changes the approach (dumping context) then we can surely do so.

We cannot unfortunately completely remove the context from the project as it would break hiding of the messages for a lot of people using and relying on such behaviour.

Let me know your thoughts.

Thanks,
